### ISSUE TITLE
Change harvester's server => host and server => port to environment variable values

### ISSUE THREAD

**Issue by virtuman** [blacklabelops/logio#3]
It would be nice to be able to use exporter's end point via ENV variables which would allow to use harvester's on external nodes as well.

```
logio_server='logio';
logio_server_port=28777;

if [ -n "${LOGIO_SERVER}" ]; then
  logio_server=${LOGIO_SERVER}
fi
if [ -n "${LOGIO_SERVER_PORT}" ]; then
  logio_server_port=${LOGIO_SERVER_PORT}
fi
```

**Comment by blacklabelops** [comment]
Implemented:

You can specify the logio master host and port with:
- LOGIO_HARVESTER_MASTER_HOST (default: `logio`)
- LOGIO_HARVESTER_MASTER_PORT (default: `28777`)

**Comment by virtuman** [comment]
thank you very much !
