### ISSUE TITLE
How to use in a subdirectory

### ISSUE THREAD

**Issue by kujiy** [blacklabelops/logio#4]
Hi, thank you for sharing your great project. I'd like to use this containers inside a subdirectory like `http://example.com/logio/` . I'm using haproxy in front of logio like a ProxyPass. Is it possible that logio serves requests as under a directory?

**Comment by blacklabelops** [comment]
The log.io project page can be found here: https://github.com/NarrativeScience/Log.io

In have not found any way to configure the expected application path. You either have to ask the project or use a subdomain, e.g. http://logio.example.com
