### ISSUE TITLE
Recurring crashes (not sure why)

### ISSUE THREAD

**Issue by that1guy** [blacklabelops/logio#7]
Hello,

One of my logging directories must be doing something weird (I have no idea what, or which one is causing the issue).

Basically `harvester` crashes at the exact same time every time.  When I do `docker logs -f harvester` is see this when it crashes.

```
node: ../deps/uv/src/unix/linux-inotify.c:230: uv__fs_event_close: Assertion `w != ((void *)0)' failed.
/opt/logio/docker-entrypoint.sh: line 16:   101 Aborted                 (core dumped) log.io-harvester
```

Here is a screencast of my issue so you can see it in action... https://screencast.com/t/D5tEVz0EEn

My question is, how do I determine which logging directory is causing this issue without really cumbersome process of elimination?  Any further logs I can inspect?

**Comment by blacklabelops** [comment]
I would advice you to open a ticket on the log.io repository. `node:` looks like a log.io error message and perhaps those guys can tell what's happening: `Assertion `w != ((void *)0)' failed.`
